apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret-letsencrypt-prod-keycloak
  namespace: keycloak
spec:
  secretName: tls-secret-letsencrypt-prod-keycloak
  dnsNames:
  - keycloak.reclada.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - keycloak.reclada.com
  issuerRef:
    name: letsencrypt-prod-keycloak
    kind: ClusterIssuer