webui:
  config:
    dns: &dns autotest.reclada.com
  env:
    ENVIRONMENT: autotest

ingress:
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: dev-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  #   nginx.ingress.kubernetes.io/whitelist-source-range: "34.254.195.254/32,34.252.71.5/32,52.149.163.72/32,168.63.48.145/32"
  hosts:
    - host: *dns
      paths:
        - /
  # tls:
  #  - secretName: tls-secret-letsencrypt-prod-dev
  #    hosts:
  #      - *dns