webui:
  config:
    dns: &dns dynamicenvname.reclada.com
  env:
    ENVIRONMENT: dynamicenvname

clusterissuer:
  prod:
    name: letsencrypt-prod-dynamicenvname
    enabled: true
    privateKeySecretRef: tls-secret-letsencrypt-prod-dynamicenvname
    email: maksim.vasilev@quantori.com  # declare a valid email here, even for staging!
  staging:
    name: letsencrypt-staging-dynamicenvname
    enabled: false
    privateKeySecretRef: tls-secret-letsencrypt-staging-dynamicenvname
    email: maksim.vasilev@quantori.com  # declare a valid email here, even for staging!


ingress:
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: dev-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  hosts:
    - host: *dns
      paths:
        - /
  tls:
   - secretName: tls-secret-letsencrypt-staging-dynamicenvname
     hosts:
       - *dns