version: '3.3'

networks:
  network:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      driver: default
      config:
        - subnet: 10.4.1.0/24

services:
  sandbox:
    image: postgrest:latest
    networks:
      - network
    working_dir: /root
    ports:
      - '80:80'
    environment:
      PATH: 'bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    command: './run.sh'
